# Site wide configuration

title:            The Sqor Blog
locale:           en_US
url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

         
# Site owner
owner:
  name: Sqor, Inc.
  avatar: sqor.png
  bio: "Sqor is a groundbreaking social gaming and publishing platform that delivers content from more professional and amateur athletes."
  email: "feedback@sqor.com"
  location: "San Francisco, CA"
  disqus-shortname: 
  twitter: sqor
  facebook: sqor
  instgram: sqor
  google:
    analytics: UA-38230514-4
    verify: 
    ad-client: 
    ad-slot: 
  pinterest: sqor

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
